In [1]:
import numpy as np
import pandas as pd

def linear_algebra_operations():
    print("=== Linear Algebra Operations ===")

    # Matrix creation
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

    print("\nMatrix A:\n", A)
    print("Matrix B:\n", B)

    # Basic operations
    print("\nA + B:\n", A + B)
    print("A - B:\n", A - B)
    print("Element-wise A * B:\n", A * B)
    print("Matrix Multiplication A @ B:\n", A @ B)
    print("Transpose of A:\n", A.T)

    # Eigenvalues and Eigenvectors
    eigvals, eigvecs = np.linalg.eig(A)
    print("\nEigenvalues of A:\n", eigvals)
    print("Eigenvectors of A:\n", eigvecs)

    # Inverse
    inv_A = np.linalg.inv(A)
    print("\nInverse of A:\n", inv_A)

    # Solve linear system Ax = b
    A_sys = np.array([[2, 1], [1, 3]])
    b = np.array([8, 13])
    x = np.linalg.solve(A_sys, b)
    print("\nSolving Ax = b:")
    print("A:\n", A_sys)
    print("b:\n", b)
    print("Solution x:\n", x)


def probability_simulations():
    print("\n=== Probability Simulations ===")

    # Dice roll simulation
    rolls = np.random.randint(1, 7, size=10000)
    roll_series = pd.Series(rolls)
    roll_probs = roll_series.value_counts(normalize=True).sort_index()
    print("\nDice Roll Probabilities (10,000 rolls):\n", roll_probs)

    # Coin toss simulation
    tosses = np.random.randint(0, 2, size=1000)
    toss_series = pd.Series(tosses).map({0: 'Heads', 1: 'Tails'})
    toss_counts = toss_series.value_counts()
    print("\nCoin Toss Counts (1000 tosses):\n", toss_counts)

    # Normal distribution sampling
    samples = np.random.normal(loc=0, scale=1, size=5000)
    sample_series = pd.Series(samples)
    print("\nNormal Distribution Sample Summary (5000 samples):\n", sample_series.describe())


if __name__ == "__main__":
    linear_algebra_operations()
    probability_simulations()


=== Linear Algebra Operations ===

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

A + B:
 [[ 6  8]
 [10 12]]
A - B:
 [[-4 -4]
 [-4 -4]]
Element-wise A * B:
 [[ 5 12]
 [21 32]]
Matrix Multiplication A @ B:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]

Eigenvalues of A:
 [-0.37228132  5.37228132]
Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Solving Ax = b:
A:
 [[2 1]
 [1 3]]
b:
 [ 8 13]
Solution x:
 [2.2 3.6]

=== Probability Simulations ===

Dice Roll Probabilities (10,000 rolls):
 1    0.1765
2    0.1595
3    0.1673
4    0.1646
5    0.1683
6    0.1638
dtype: float64

Coin Toss Counts (1000 tosses):
 Tails    503
Heads    497
dtype: int64

Normal Distribution Sample Summary (5000 samples):
 count    5000.000000
mean        0.001157
std         0.998093
min        -3.638923
25%        -0.681448
50%        -0.003249
75%         0.663627
max         4.420926
dtype: float64
