In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

# Matrix addition
add = A + B

# Matrix multiplication
mult = np.dot(A, B)

# Transpose
transpose_A = A.T

# Inverse
inv_A = np.linalg.inv(A)

print("Addition:\n", add)
print("Multiplication:\n", mult)
print("Transpose of A:\n", transpose_A)
print("Inverse of A:\n", inv_A)


Addition:
 [[3 2]
 [4 7]]
Multiplication:
 [[ 4  6]
 [10 12]]
Transpose of A:
 [[1 3]
 [2 4]]
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
